name: Run Tests
on: [push]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.19'
      - name: Run Tests
        run: go test -v ./...