name: Run Tests

on: [push]

jobs:
  list-modules:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }}
    steps:
      - uses: actions/checkout@v2
      - id: set-dirs
        # List all reps that contain a go.mod file.
        run: echo "::set-output name=dir::$(find . -name 'go.mod' -printf '%P\n' | xargs dirname | jq -R -s -c 'split("\n")[0:-1]')"
        # Define step output named dir base on ls command transformed to JSON thanks to jq

  test-modules:
    runs-on: ubuntu-latest
    needs: [list-modules]
    continue-on-error: true
    strategy:
      matrix:
        dir: ${{fromJson(needs.list-modules.outputs.dir)}}
    steps:
      - run: echo Building ${{ matrix.dir }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run Tests
        working-directory: ${{ matrix.dir }}
        run: go test -v